In [120]:
import numpy as np
import time

In [121]:
arr1 = np.arange(1, 11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [122]:
arr2 = np.arange(1,10).reshape((3,3))
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
arr3 = np.round((np.random.rand(3, 5, 3))*10, 2)
arr3

array([[[ 6.72,  3.91,  9.28],
        [ 1.17,  8.76,  5.09],
        [ 5.69,  6.55,  6.27],
        [ 9.38,  2.29,  3.15],
        [ 0.23,  2.8 ,  7.51]],

       [[ 9.14,  2.  ,  0.58],
        [ 0.54,  4.62,  9.12],
        [ 6.54,  6.67,  1.58],
        [ 7.17,  2.62, 10.  ],
        [ 9.14,  1.97,  0.28]],

       [[ 6.1 ,  6.43,  1.48],
        [ 1.76,  3.1 ,  2.79],
        [ 4.95,  5.49,  9.9 ],
        [ 2.22,  5.73,  8.37],
        [ 7.38,  3.34,  5.93]]])

In [124]:
print('--arr1--' )
print(arr1.size)
print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype)
print(arr1.itemsize)
print(arr1.nbytes)

print('--arr2--' )
print(arr2.shape)
print(arr2.size)
print(arr2.ndim)
print(arr2.dtype)
print(arr2.nbytes)
print(arr2.itemsize)

print('--arr3--' )
print(arr3.size)
print(arr3.shape)
print(arr3.ndim)
print(arr3.dtype)
print(arr3.itemsize)
print(arr3.nbytes)

--arr1--
10
(10,)
1
int64
8
80
--arr2--
(3, 3)
9
2
int64
72
8
--arr3--
45
(3, 5, 3)
3
float64
8
360


In [125]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90] 
arr4 = np.array(data)
first_three = arr4[:3]
alternate_elements = arr4[::2]
reversed_array = arr4[::-1]

In [126]:
print(arr4)
print(first_three)
print(alternate_elements)
print(reversed_array)

[10 20 30 40 50 60 70 80 90]
[10 20 30]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]


In [127]:
A = np.random.randint(1, 20, 5)
B = np.random.randint(1, 20, 5)
A, B

(array([12,  9,  3, 17, 11], dtype=int32),
 array([15,  2, 11, 14, 17], dtype=int32))

In [128]:
print(A + B)
print(A - B)
print(A * B)
print(A / B)

[27 11 14 31 28]
[-3  7 -8  3 -6]
[180  18  33 238 187]
[0.8        4.5        0.27272727 1.21428571 0.64705882]


In [129]:
print(np.dot(A,B))

656


In [130]:
print(np.mean(A))
print(np.median(A))
print(np.std(A))
print(np.var(A))

10.4
11.0
4.5431266766402185
20.64


In [131]:
print('ele:', 'index', sep='\t')
print(f'{np.min(B)} (min)', np.argmin(B), sep='\t')
print(f'{np.max(B)} (min)', np.argmax(B), sep='\t')

ele:	index
2 (min)	1
17 (min)	4


In [132]:
arr5 = np.arange(1, 13)

In [133]:
reshaped_arr = np.reshape(arr5, (4, 3))
np.reshape(arr5, (2, 2, 3))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [134]:
transposed_arr = reshaped_arr.T
print(transposed_arr)
print(reshaped_arr.shape)
print(transposed_arr.shape)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
(4, 3)
(3, 4)


In [135]:
arr6 = np.random.randint(10, 50, 15)
arr6

array([19, 28, 37, 23, 12, 25, 49, 23, 27, 33, 24, 42, 23, 28, 16],
      dtype=int32)

In [136]:
print(arr6[arr6>25])
# print(np.where(arr6>25)) # returns indices of elements in arr6 that are greater than 25
arr6[arr6<30] = 0
print(arr6)
arr6[arr6%5 == 0].shape

[28 37 49 27 33 42 28]
[ 0  0 37  0  0  0 49  0  0 33  0 42  0  0  0]


(11,)

1. Use NumPy's built-in functions to:  
o Create an array of 10 equally spaced values between 0 and 1. 
o Create an identity matrix of size 4x4. 
o Generate a 1D array of 20 random integers between 1 and 100, 
sort it, and find the 5 largest elements. 

In [137]:
arr7 = np.linspace(0, 1, 10)

matrix_I = np.eye(4)

arr8 = np.random.randint(1, 101, 20)

sorted_array = np.sort(arr8)

print(sorted_array[-5:])

[80 82 82 92 99]


In [ ]:
size = 100

array1 = np.random.rand(size, size)
array2 = np.random.rand(size, size)

start_time = time.time()
result_matrix = np.matmul(array1, array2)
end_time = time.time()
matrix_multiplication_time = end_time - start_time
print("Matrix Multiplication Time: {:.6f} seconds".format(matrix_multiplication_time))

start_time = time.time()
try:
    determinant = np.linalg.det(result_matrix)
except np.linalg.LinAlgError:
    determinant = "Not possible (matrix is singular)"
end_time = time.time()
determinant_time = end_time - start_time
print("Determinant: {}".format(determinant))
print("Determinant Time: {:.6f} seconds".format(determinant_time))

start_time = time.time()
try:
    inverse = np.linalg.inv(result_matrix)
except np.linalg.LinAlgError:
    inverse = "Not possible (matrix is singular)"
end_time = time.time()
inverse_time = end_time - start_time
print("Inverse: {}".format(inverse))
print("Inverse Time: {:.6f} seconds".format(inverse_time))

Matrix Multiplication Time: 0.002513 seconds
Determinant: 1.7003913518856374e+48
Determinant Time: 0.000000 seconds
Inverse: [[ -47.3658661    76.09983737    1.50213173 ... -241.25274832
    25.97525494   24.05894123]
 [  34.14442136  -50.81993244   -5.62244575 ...  161.80685092
   -16.99896732  -13.91824504]
 [  52.89760442  -80.26209388   -3.48927009 ...  257.67876326
   -28.26565587  -22.94359957]
 ...
 [ -81.62000567  127.89880925    8.49709969 ... -405.08480055
    43.67994931   39.72982518]
 [  67.53620852 -103.22047299   -8.21715235 ...  329.31866139
   -36.0869253   -28.44487249]
 [ -23.53321026   35.01962253    2.35051075 ... -113.27027994
    12.06959601    9.12446963]]
Inverse Time: 0.311130 seconds
