<div style="font-size: 10px">

# 🧠 NumPy Interactive Revision README

>NumPy (Numerical Python) is the foundational package for numerical computing in Python. It provides high-performance multidimensional arrays and tools for working with them. It is written in C/C++ to make internal operations as efficient(fast) as possible.

---

## ✅ Import NumPy
```python
import numpy as np
```

---

## 📂 1. Array Creation
```python
np.array([1, 2, 3])            # From list
np.zeros((2, 3))               # 2x3 matrix of 0s
np.ones((3,))                  # Vector of 1s
np.full((2, 2), 9)             # 2x2 matrix filled with 9
np.eye(3)                      # 3x3 identity matrix
np.arange(1, 10, 2)            # [1 3 5 7 9]
np.linspace(0, 1, 5)           # [0. , 0.25, 0.5, 0.75, 1. ]
np.random.rand(2, 2)           # Random in [0,1)
np.random.randn(2)             # Std normal values
np.random.randint(0, 10, 5)    # Random integers
```

---

## 📊 2. Array Attributes
```python
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape      # (2, 3)
a.ndim       # 2
a.size       # 6
a.dtype      # dtype('int64')
a.itemsize   # 8 bytes per item
a.nbytes     # Total 48 bytes
```

---

## 🔁 3. Reshaping & Flattening
```python
a.reshape((3, 2))         # Change shape
np.ravel(a)               # Flatten (view)
a.flatten()               # Flatten (copy)
a.T                       # Transpose
np.reshape(a, (-1,))      # Auto reshape
```

---

## 📂 4. Indexing, Slicing, Iterating
```python
a[0, 1]                   # Access
b = a[:, 1]               # Column
c = a[1, :]               # Row
a[::2]                    # Every 2nd row
np.where(a > 3)           # Indices where condition met
np.take(a, [1, 4])        # Indexed elements
np.put(a, [1, 4], 99)     # Replace values
```

---

## ➕ 5. Mathematical Operations
```python
x + y
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)
np.abs(x)
np.round(x, 2)
```

---

## 📊 6. Aggregations & Stats
```python
np.sum(a)
np.mean(a)
np.median(a)
np.std(a)
np.var(a)
np.min(a), np.max(a)
np.argmin(a), np.argmax(a)
np.percentile(a, 50)
np.cumsum(a)
np.cumprod(a)
```

---

## 🔣 7. Logical Operations
```python
np.all(a > 0)
np.any(a < 0)
np.isfinite(a)
np.isnan(a)
np.where(a > 2, a, 0)
```

---

## 📚 8. Linear Algebra (np.linalg)
```python
np.dot(A, B)
np.matmul(A, B)
np.linalg.inv(A)
np.linalg.det(A)
np.linalg.eig(A)
np.linalg.solve(A, b)
np.linalg.norm(A)
```

---

## 🔗 9. Stacking & Splitting
```python
np.concatenate([a, b], axis=0)
np.stack([a, b], axis=1)
np.hstack((a, b))
np.vstack((a, b))
np.split(a, 2)
np.hsplit(a, 2)
np.vsplit(a, 2)
```

---

## 🧼 10. Cleaning, Sorting
```python
np.sort(a)
np.argsort(a)
np.unique(a)
np.trim_zeros([0, 0, 1, 2, 0])
np.delete(a, [1, 3])
```

---

## 🔄 11. Broadcasting & Vectorization
```python
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])
a + b    # Broadcasting example
```

---

## 🧪 12. Random Module
```python
np.random.rand(3)
np.random.randn(2, 2)
np.random.randint(1, 10, (2, 3))
np.random.choice([1, 2, 3, 4])
np.random.seed(42)        # Reproducible output
```

---

## 🛠️ 13. Utility Functions
```python
np.copy(a)
np.clip(a, 0, 10)
np.tile(a, (2, 1))
np.repeat(a, 2)
np.round(a, 2)
```

---

## 📦 14. Saving and Loading
```python
np.save('array.npy', a)
a = np.load('array.npy')
np.savetxt('array.csv', a, delimiter=',')
a = np.loadtxt('array.csv', delimiter=',')
```

---

## 🗒️ Notes
- Use `dtype=np.float32/int32` in creation for performance.
- Always set `random.seed()` for reproducibility in ML.
- `np.newaxis` can help in reshaping dimensions easily.

---

> 💡 **Tip**: Practice writing your own matrix functions using only NumPy to build deeper mastery.

</div>


In [3]:
import numpy as np
print(np.__version__)

2.3.1


In [4]:
l1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr1 = np.array(l1)
print(arr1, type(arr1))

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>


In [10]:
l2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr2 = np.array(l2)
arr2[2,0]
arr2[-1, 0] # last row, first column

np.int64(7)

In [16]:
print(arr1.shape)
print(arr2.shape)
print(arr1.ndim)
print(arr2.ndim)

(10,)
(3, 3)
1
2


In [23]:
# zagged array concept
arr3 = np.array([[1, 2, 3], [4, 5]], dtype = 'O')
print(arr3, type(arr3))
print(arr3.shape)
print(arr3.ndim)
print(arr3[0], type(arr3[0]))
print(arr3[0][1], type(arr3[0][1]))

[list([1, 2, 3]) list([4, 5])] <class 'numpy.ndarray'>
(2,)
1
[1, 2, 3] <class 'list'>
2 <class 'int'>


In [29]:
# arange, linspace, ones, zeroes, eye, diag
print(np.arange(1, 11, 1, dtype = 'f4'))
print(np.linspace(1, 2, 4, dtype = 'f4'))
shape = [1, 2, 2]
print(np.ones(shape, dtype = 'f4'))
print(np.zeros(shape, dtype = 'f4'))
print(np.eye(3, dtype = 'f4'))
print(np.diag([1, 2, 3, 4]))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1.        1.3333334 1.6666666 2.       ]
[[[1. 1.]
  [1. 1.]]]
[[[0. 0.]
  [0. 0.]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
